import type { Metadata } from "next";
import { manrope, playfair } from "@/app/fonts"; 
import "./globals.css"; 
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";
import NewsLetterSection from "@/components/NewsLetterSection/page";
import { ThemeProvider } from "@/components/Theme/themeProvider"

export const metadata: Metadata = {
  title: "Fabrix.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${manrope.variable} ${playfair.variable}`}>
      <body className="antialiased">
        
        <ThemeProvider >
          {/* header */}
          <Header/>
            <div>
              {children}
            </div>
          {/* Footer with NewsLetter*/}
          <NewsLetterSection/>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
